### ISSUE TITLE
IE11 cloneNode behaves unexpectedly

### ISSUE THREAD

**Issue by daffl** [canjs/can-view-target#18]
It turns out that text nodes containing text with a `-` will be turned into several text nodes in IE11:

```js
var frag = document.createDocumentFragment();
var text = document.createTextNode('some-text');

frag.appendChild(text);

var clone = frag.cloneNode(true);

// clone.childNodes.length -> 3 instead of 1
```

Due to this we have to fall back to the less performant node cloning already used in IE 9 and 10 for now. 

Possible optimizations could be to re-consolidate multiple adjacent text nodes if they initially contained a `-` (also see [Node.normalize](https://developer.mozilla.org/en-US/docs/Web/API/Node/normalize)).

**Comment by phillipskevin** [comment]
I found that `cloneNode` only behaves incorrectly after we [set up a MutationObserver](https://github.com/canjs/can-util/blob/master/dom/mutation-observer/document/document.js#L14) on the `documentElement`. 

```
var frag = document.createDocumentFragment();
var text = document.createTextNode('some-text');
var observer = new MutationObserver(function(mutations) {});

frag.appendChild(text);

var clone = frag.cloneNode(true);
// clone.childNodes.length -> 1

observer.observe(document.documentElement, { childList: true, subtree: true });
clone = frag.cloneNode(true);
// clone.childNodes.length -> 3
```
