### ISSUE TITLE
Remove cloneNode code?

### ISSUE THREAD

**Issue by phillipskevin** [canjs/can-view-target#65]
![image](https://user-images.githubusercontent.com/5851984/40563802-c178b482-602b-11e8-888c-d46763c82fbf.png)

https://github.com/canjs/can-view-target/blob/9cb4a0a8647419429152764d43263bcbbd12990a/can-view-target.js#L85-L128

**Comment by cherifGsoul** [comment]
It can not be removed, the `cloneNode` is needed for `IE11` :
https://github.com/canjs/can-view-target/blob/864763c18c2bbf8f1566b7735984923cd360e0d2/can-view-target.js#L49
